active_experiment: dynamic_pool_with_reemission
learning_mode: social   # self | social

context:
  p: 1
  t_received: 1
  t_summary: 1

defaults:
  num_knowledge_agents: 10
  ground_truth_key: ground_truth_1
  environment:
    width: 750
    height: 750
  num_snapshots: 400
  snapshot_interval_seconds: 3.0

experiments:
  baseline:
    information_teleportation:
      enabled: false

  dynamic_pool_with_reemission:
    information_teleportation:
      enabled: true
      mode: dynamic_pool_with_reemission
      active_ratio: 0.2
      mean_swap_time: 10.0

  dynamic_pool_without_reemission:
    information_teleportation:
      enabled: true
      mode: dynamic_pool_without_reemission
      active_ratio: 0.2
      mean_swap_time: 10.0
